fn main() { println!("Hello, World! Calculator"); // Add more calculations here }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } // Example calculation println!("The sum is: {}", add(5, 3)); }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } // Example calculation println!("The sum is: {}", add(5, 3)); }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
fn main() { fn add(x: i32, y: i32) -> i32 { x + y } fn subtract(x: i32, y: i32) -> i32 { x - y } fn multiply(x: i32, y: i32) -> i32 { x * y } fn divide(x: i32, y: i32) -> i32 { if y == 0 { println!("Error: Division by zero"); return 0; } else { x / y } } fn main() { let x: i32; let y: i32; let operation: String; println!("Enter two numbers and an operation (+, -, *, /):"); std::io::stdin().read_line(&mut std::io::Stdio::stdin().lock().unwrap()).unwrap(); } }
